name: Run Backend

on:
  push:
    branches: [ main ]

jobs:
  run-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Create .env file from Secrets
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> backend/.env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> backend/.env

      - name: Run backend
        run: |
          cd backend
          python run.py
